export const PRESUPUESTO_REPARACION_ESTADOS = Object.freeze({
  PENDING: "PENDING",
  ACEPTADA: "ACEPTADA",
  RECHAZADA: "RECHAZADA",
  EXPIRADA: "EXPIRADA",
  FINALIZADA: "FINALIZADA",
});

export const PRESUPUESTO_REPARACION_ESTADOS_LIST = Object.freeze(
  Object.values(PRESUPUESTO_REPARACION_ESTADOS)
);
