export const REPARACION_ESTADOS = Object.freeze({
  CREADA: "CREADA",
  PENDIENTE_PRESUPUESTO: "PENDIENTE_PRESUPUESTO",
  PENDIENTE_ACEPTACION: "PENDIENTE_ACEPTACION",
  PRESUPUESTO_ACEPTADO: "PRESUPUESTO_ACEPTADO",
  TERMINADA: "TERMINADA",
  CANCELADA: "CANCELADA",
});

export const REPARACION_ESTADOS_LIST = Object.freeze(Object.values(REPARACION_ESTADOS));