export const SERVICE_CONTRACT_TYPES = Object.freeze({
  PREVENTIVO: "PREVENTIVO",
  TODO_INCLUIDO: "TODO_INCLUIDO",
});

export const SERVICE_CONTRACT_STATES = Object.freeze({
  BORRADOR: "BORRADOR",
  PENDIENTE_FIRMA_CLIENTE: "PENDIENTE_FIRMA_CLIENTE",
  PENDIENTE_FIRMA_TECARRAL: "PENDIENTE_FIRMA_TECARRAL",
  ACTIVO: "ACTIVO",
  CANCELADO: "CANCELADO",
  VENCIDO: "VENCIDO",
});

export const SERVICE_VISIT_STATES = Object.freeze({
  PENDIENTE: "PENDIENTE",
  REALIZADA: "REALIZADA",
  OMITIDA: "OMITIDA",
  REPROGRAMADA: "REPROGRAMADA",
  VENCIDA: "VENCIDA",
});

export const SERVICE_CONTEXT_TYPES = Object.freeze({
  ALQUILER: "ALQUILER",
  CONTRATO_MANTENIMIENTO: "CONTRATO_MANTENIMIENTO",
  REPARACION_PUNTUAL_CLIENTE: "REPARACION_PUNTUAL_CLIENTE",
});

export const COVERAGE_DECISIONS = Object.freeze({
  CLIENTE: "CLIENTE",
  TECARRAL: "TECARRAL",
});

export const COVERAGE_REASONS = Object.freeze({
  PREVENTIVO_NO_CUBRE: "PREVENTIVO_NO_CUBRE",
  TODO_INCLUIDO: "TODO_INCLUIDO",
  GOLPE_ACCIDENTE: "GOLPE_ACCIDENTE",
  REPARACION_PUNTUAL: "REPARACION_PUNTUAL",
  OTRO: "OTRO",
});

export const FAULT_CAUSES = Object.freeze({
  DESGASTE_USO: "DESGASTE_USO",
  GOLPE_ACCIDENTE: "GOLPE_ACCIDENTE",
});

export const LOANER_ASSIGNMENT_STATES = Object.freeze({
  RESERVADA: "RESERVADA",
  ENTREGADA: "ENTREGADA",
  DEVUELTA: "DEVUELTA",
  CANCELADA: "CANCELADA",
});

export const NOTIFICATION_TYPES = Object.freeze({
  MANTENIMIENTO_PROXIMO: "MANTENIMIENTO_PROXIMO",
  MANTENIMIENTO_HOY: "MANTENIMIENTO_HOY",
  MANTENIMIENTO_ATRASADO_2_DIAS: "MANTENIMIENTO_ATRASADO_2_DIAS",
  MANTENIMIENTO_ATRASADO_7_DIAS: "MANTENIMIENTO_ATRASADO_7_DIAS",
  CONTRATO_FIRMADO: "CONTRATO_FIRMADO",
  PRESUPUESTO_PENDIENTE_FIRMA: "PRESUPUESTO_PENDIENTE_FIRMA",
});

export const CUSTOMER_RELATIONSHIP_TYPES = Object.freeze({
  CLIENTE_HABITUAL: 'CLIENTE_HABITUAL',
  CLIENTE_NUEVO: 'CLIENTE_NUEVO',
});

export const SERVICE_VISIT_KINDS = Object.freeze({
  PRIMERA_VISITA: 'PRIMERA_VISITA',
  REVISION: 'REVISION',
  REPARACION: 'REPARACION',
  PRESUPUESTO_PREVIO: 'PRESUPUESTO_PREVIO',
  PEDIDO_RECAMBIO: 'PEDIDO_RECAMBIO',
});

export const ALBARAN_DOCUMENT_KINDS = Object.freeze({
  ALBARAN: 'ALBARAN',
  PRESUPUESTO: 'PRESUPUESTO',
  PEDIDO: 'PEDIDO',
  SERVICIO_TECNICO: 'SERVICIO_TECNICO',
});

export const ALBARAN_PRICING_MODES = Object.freeze({
  FACTURAR_POSTERIOR: 'FACTURAR_POSTERIOR',
  PREVISION_GASTO_FIJA: 'PREVISION_GASTO_FIJA',
  COSTE_CERO: 'COSTE_CERO',
});
