import { StyleSheet } from 'react-native';

import { AppColors } from '@/constants/theme';
import { TAB_BAR_HORIZONTAL_PADDING, TAB_BAR_INNER_PADDING } from '@/constants/home';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.background,
  },
  keyboardContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  homeContent: {
    position: 'relative',
    paddingTop: 18,
  },
  homeLogo: {
    alignSelf: 'center',
    width: 190,
    height: 54,
    marginBottom: 18,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  searchInputWrapper: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.secondary65,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: AppColors.inputText,
    fontSize: 15,
    paddingVertical: 0,
  },
  filterButton: {
    minWidth: 92,
    height: 42,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.secondary65,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  addMachineButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonText: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '500',
  },
  suggestionsBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AppColors.primary20,
    backgroundColor: AppColors.background,
    marginBottom: 12,
    overflow: 'hidden',
  },
  suggestionItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.primary20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  suggestionText: {
    color: AppColors.text,
    fontSize: 14,
    flexShrink: 1,
  },
  suggestionSource: {
    color: AppColors.primary50,
    fontSize: 12,
    marginLeft: 10,
    textTransform: 'capitalize',
  },
  filterPanelWrapper: {
    position: 'absolute',
    top: 88,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  filterPanelSpacer: {
    height: 440,
  },
  filterPanel: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: '#66B2C6',
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 16,
  },
  filterCloseButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 1,
  },
  filterSection: {
    marginBottom: 16,
  },
  filterSectionTitle: {
    color: AppColors.background,
    fontSize: 18,
    fontWeight: '500',
    marginBottom: 10,
  },
  filterChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: AppColors.primary,
  },
  filterChipText: {
    color: AppColors.primary,
    fontSize: 13,
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: AppColors.background,
  },
  machineListContent: {
    paddingTop: 10,
    paddingBottom: 6,
  },
  machineGridRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  machineCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.background,
    overflow: 'hidden',
  },
  machineMedia: {
    height: 116,
    backgroundColor: '#CFEAF2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  machineImage: {
    width: '100%',
    height: 96,
  },
  machineInfo: {
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 3,
  },
  machineLine: {
    color: '#222222',
    fontSize: 11,
    lineHeight: 14,
  },
  machineLabel: {
    color: AppColors.primary,
    fontWeight: '700',
  },
  detailContainer: {
    paddingTop: 24,
    paddingBottom: 24,
  },
  detailHero: {
    marginHorizontal: -24,
    minHeight: 280,
    backgroundColor: '#A9D9E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -24,
    marginBottom: 18,
    overflow: 'hidden',
  },
  detailCloseButton: {
    position: 'absolute',
    top: 18,
    left: 18,
    zIndex: 2,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 18,
  },
  detailImage: {
    width: '100%',
    height: 250,
  },
  detailTitle: {
    color: AppColors.primary,
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 14,
  },
  detailLine: {
    color: '#111111',
    fontSize: 16,
    lineHeight: 24,
  },
  detailLabel: {
    color: '#111111',
    fontWeight: '600',
  },
  detailValue: {
    color: AppColors.primary,
  },
  detailActionsRow: {
    gap: 10,
    marginTop: 10,
    marginBottom: 4,
  },
  detailActionsColumn: {
    flex: 1,
  },
  selectorBlock: {
    marginBottom: 8,
  },
  selectorButton: {
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  selectorButtonDisabled: {
    opacity: 0.6,
  },
  selectorButtonText: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '500',
  },
  selectorList: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    marginTop: 6,
    overflow: 'hidden',
  },
  selectorListItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.primary20,
  },
  selectorListItemText: {
    color: AppColors.primary,
    fontSize: 14,
  },
  incidencePanel: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: AppColors.primary20,
    backgroundColor: '#F7FBFD',
    padding: 12,
  },
  incidenceHint: {
    color: AppColors.text,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  incidenceInput: {
    minHeight: 96,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.background,
    color: AppColors.inputText,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
    marginBottom: 10,
  },
  primaryActionButton: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: AppColors.primary20,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 18,
  },
  primaryActionButtonText: {
    color: AppColors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryActionButton: {
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: AppColors.primary20,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  secondaryActionButtonBlock: {
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: AppColors.background,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginTop: 10,
  },
  secondaryActionButtonText: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  inlineActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  inlineActionButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
  },
  inlineActionButtonText: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  sectionBlock: {
    marginTop: 20,
  },
  mapsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mapsTextBlock: {
    flex: 1,
  },
  mapsActionButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.primary20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionTitle: {
    color: AppColors.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionHint: {
    color: AppColors.text,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  acceptedProposalText: {
    color: AppColors.success,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  proposalCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AppColors.primary20,
    backgroundColor: '#F7FBFD',
    padding: 12,
    marginBottom: 10,
  },
  proposalCardTitle: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  proposalCardLine: {
    color: '#111111',
    fontSize: 13,
    lineHeight: 19,
  },
  proposalSummaryCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AppColors.primary20,
    backgroundColor: '#F7FBFD',
    padding: 14,
    marginBottom: 14,
  },
  proposalSummaryTitle: {
    color: AppColors.primary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  formBackButton: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    marginBottom: 14,
  },
  formBackButtonText: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  formFieldLabel: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 6,
  },
  formInput: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.background,
    color: AppColors.inputText,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  machineImagePreviewCard: {
    height: 170,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: AppColors.primary20,
    backgroundColor: '#F7FBFD',
    overflow: 'hidden',
    marginBottom: 12,
  },
  machineImagePreview: {
    width: '100%',
    height: '100%',
  },
  dateFieldBlock: {
    marginBottom: 10,
  },
  formInputButton: {
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: AppColors.primary50,
    backgroundColor: AppColors.background,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  formInputButtonText: {
    color: AppColors.inputText,
    fontSize: 15,
    flex: 1,
    marginRight: 10,
  },
  formInputPlaceholder: {
    color: AppColors.primary50,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  datePickerCard: {
    backgroundColor: AppColors.background,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1.5,
    borderColor: AppColors.primary20,
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  datePickerTitle: {
    color: AppColors.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  datePickerMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  datePickerMonthButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.primary20,
  },
  datePickerMonthLabel: {
    color: AppColors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  calendarWeekday: {
    width: '14.28%',
    textAlign: 'center',
    color: AppColors.primary50,
    fontSize: 12,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 14,
  },
  calendarDay: {
    width: '14.28%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  calendarDaySelected: {
    backgroundColor: AppColors.primary,
  },
  calendarDayText: {
    color: AppColors.primary,
    fontSize: 14,
  },
  calendarDayTextMuted: {
    color: AppColors.primary50,
  },
  calendarDayTextSelected: {
    color: AppColors.background,
    fontWeight: '700',
  },
  datePickerSectionTitle: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  timePickerRow: {
    marginBottom: 12,
  },
  timePickerWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  timeChip: {
    minWidth: 52,
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginRight: 8,
  },
  timeChipActive: {
    backgroundColor: AppColors.primary,
  },
  timeChipText: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  timeChipTextActive: {
    color: AppColors.background,
  },
  datePickerFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 4,
  },
  datePickerSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.background,
  },
  datePickerSecondaryText: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  datePickerPrimaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AppColors.secondary,
  },
  datePickerPrimaryText: {
    color: AppColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  datePickerPreview: {
    color: AppColors.primary50,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 10,
  },
  navigationModalCard: {
    backgroundColor: AppColors.background,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1.5,
    borderColor: AppColors.primary20,
  },
  navigationOptionButton: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    marginTop: 10,
  },
  navigationOptionText: {
    color: AppColors.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  feedbackText: {
    color: AppColors.error,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 10,
  },
  successFeedbackText: {
    color: '#2f8f4e',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: '600',
  },
  feedbackTextWithFilter: {
    marginTop: 12,
  },
  loadingText: {
    color: AppColors.text,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 10,
  },
  emptyState: {
    paddingVertical: 36,
  },
  emptyStateText: {
    color: AppColors.primary,
    fontSize: 15,
    textAlign: 'center',
  },
  centeredBlock: {
    minHeight: 320,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 24,
    paddingBottom: 90,
    minHeight: 420,
  },
  placeholderLogo: {
    width: 180,
    height: 54,
    marginBottom: 18,
  },
  placeholderTitle: {
    color: AppColors.primary,
    fontSize: 28,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 10,
  },
  placeholderText: {
    color: AppColors.text,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 280,
  },
  tabBar: {
    position: 'absolute',
    left: TAB_BAR_HORIZONTAL_PADDING,
    right: TAB_BAR_HORIZONTAL_PADDING,
    bottom: 20,
    height: 74,
    borderRadius: 38,
    borderWidth: 1.5,
    borderColor: AppColors.primary,
    backgroundColor: AppColors.background,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: TAB_BAR_INNER_PADDING,
  },
  tabIndicator: {
    position: 'absolute',
    top: 7,
    left: 0,
    height: 60,
    borderRadius: 30,
    backgroundColor: AppColors.primary20,
  },
  tabButton: {
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
});
